framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

            # Transport dédié à la mise à jour des prix des produits
            product_price_update:
                dsn: 'doctrine://default'
                options:
                    queue_name: product_price_update
                retry_strategy:
                    max_retries: 5
                    multiplier: 2

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync

            # Route les mises à jour des prix vers le transport dédié
            App\Message\UpdatePricesMessage: product_price_update