twig:
    file_name_pattern: '*.twig'
    form_themes: [bootstrap_4_layout.html.twig]
    globals:
        app_name: 'Bictrary'
        app_url: 'https://bictrary.alwaysdata.net'
when@test:
    twig:
        strict_variables: true
