vich_uploader:
    db_driver: orm
    mappings:
        user_photo:  # Nom du mapping modifié
            uri_prefix: /users/img
            upload_destination: '%kernel.project_dir%/public/users/img'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true