vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: /users/img
            upload_destination: '%kernel.project_dir%/public/users/img'
            namer: Vich\UploaderBundle\Naming\OrignameNamer