controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_user_remove_product:
    path: /profile/product/remove/{id}
    controller: App\Controller\UserController::removeProduct
    methods: GET
