parameters:
    app.site_name: "DCSM-COMMERCE"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # On bind la variable d'environnement aux contrôleurs spécifiques
    App\Controller\GoogleController:
        bind:
            $githubToken: '%env(GITHUB_TOKEN)%'
        
    App\Controller\RegistrationController:
        bind:
            $githubToken: '%env(GITHUB_TOKEN)%'

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    NumberFormatter:
        class: 'NumberFormatter'
        arguments:
            - 'fr'
            - 1

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'