# config/services.yaml

parameters:
    users_img_directory: '%kernel.project_dir%/public/users/img'
    qr_code_directory: '%kernel.project_dir%/public/uploads/user'
    app.site_name: 'DCSM COMMERCE'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Configuration explicite pour GitHubUploader
    App\Service\GitHubUploader:
        arguments:
            $token: '%env(resolve:GITHUB_TOKEN)%'
            $repoOwner: '%env(resolve:GITHUB_REPO_OWNER)%'
            $repoName: '%env(resolve:GITHUB_REPO_NAME)%'

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(resolve:COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(resolve:COINPAYMENTS_MERCHANT_ID)%'

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'