# config/services.yaml

parameters:
    # Supprimez les paramètres intermédiaires (pas nécessaires ici)

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Configuration explicite pour GitHubUploader
    App\Service\GitHubUploader:
        public: true
        arguments:
            $token: '%env(GITHUB_TOKEN)%'
            $repoOwner: '%env(GITHUB_REPO_OWNER)%'
            $repoName: '%env(GITHUB_REPO_NAME)%'

    # Autres services
    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'