parameters:
    # Paramètres éventuels
    app.site_name: "DCSM-COMMERCE"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    Symfony\Polyfill\Intl\Icu\NumberFormatter:
        arguments:
            $locale: 'fr'
            $style: 2  # CURRENCY = 2 in NumberFormatter

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'