parameters:
    # Paramètres éventuels
    app.site_name: "DCSM-COMMERCE"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    NumberFormatter:
        class: 'NumberFormatter'
        arguments: 
            - 'fr'
            - 1 # NumberFormatter::CURRENCY constant value is 1

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'