parameters:
    # Paramètres éventuels

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\GitHubUploader:
        public: true
        arguments:
            $token: '%env(resolve:GITHUB_TOKEN)%'
            $repoOwner: '%env(resolve:GITHUB_REPO_OWNER)%'
            $repoName: '%env(resolve:GITHUB_REPO_NAME)%'

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
