parameters:
    # Paramètres éventuels

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\CryptoService:
        arguments:
            $apiKey: '%env(COINPAYMENTS_API_KEY)%'
            $merchantId: '%env(COINPAYMENTS_MERCHANT_ID)%'

    App\Middleware\ForceIndexRobotsTagMiddleware:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
